### ISSUE TITLE
Support decorator syntax when parsing with babel

### ISSUE THREAD

**Issue by 43081j** [43081j/postcss-lit#13]
Related to #9, we need to expose babel options so the user can specify language features they want to turn on/off.

@ai is there a recommended way to pass options to a custom syntax?

maybe we just attempt to read a `.babelrc` file in the working directory...

temporarily, we could add:

`['decorators', {decoratorsBeforeExport: false}]`

to support whats currently in the decorators spec

**Comment by ai** [comment]
`syntax: creator(options)`?

But I think JSON config parsers will not support it.

**Comment by abdonrd** [comment]
We have this error here:

https://github.com/IBM/pwa-lit-template/compare/stylelint-14

>SyntaxError: This experimental syntax requires enabling one of the following parser plugin(s): 'decorators-legacy, decorators' (26:0)

**Comment by 43081j** [comment]
@abdonrd i think the fix for now is to just enable whats in the decorators proposal by default

i'll get a patch version published today, then we can figure out what to do about options in the other issue

**Comment by 43081j** [comment]
Fixed in #15

**Comment by 43081j** [comment]
Published in 0.1.2

@abdonrd would be good if you could give it another try. i think you'll bump into #14 though

**Comment by abdonrd** [comment]
@43081j thanks! It works in the CLI, but not in the VSCode extension:

<img width="1148" alt="Screenshot 2021-11-26 at 22 57 10" src="https://user-images.githubusercontent.com/1007051/143657637-10cb2cab-7c52-4025-9390-967bc5ff2414.png">

Updated: https://github.com/IBM/pwa-lit-template/compare/stylelint-14

**Comment by abdonrd** [comment]
By the way, the auto fix also works:

<img width="1011" alt="Screenshot 2021-11-26 at 22 59 50" src="https://user-images.githubusercontent.com/1007051/143657745-cde621f6-a8b2-4a51-bad6-444e9a573159.png">

**Comment by iSokrat** [comment]
@43081j What's about decorators which are used in usual JS, not TS? For now, plugin reports an error for decorators which follows the latest proposal

**Comment by 43081j** [comment]
i haven't had chance to look yet but i imagine we might have to somehow expose the babel options. its unlikely we can tell babel to support both decorator specs at once, so we'd have to expose the option somehow while both exist

**Comment by iSokrat** [comment]
@43081j Yep, I agree. Actually, now I'm trying to find a way to the package in such project and it fails on the files where decorators are used. Will it be maybe possible to somehow use babel config which is used on the whole project-level (and nested configs if exist) somehow? I saw that we are using now hardcoded values, however, for example, in my app all of them are not suitable (typescript, option for decorator and jsx, although, most of them are not really disturb me for now except decorators).

```ts
export const parse: Parser<Root | Document> = (
  source: string | {toString(): string},
  opts?: Pick<ProcessOptions, 'map' | 'from'>
): Root | Document => {
  const doc = new Document();
  const sourceAsString = source.toString();
  const ast = babelParse(sourceAsString, {
    sourceType: 'unambiguous',
    plugins: [
      'typescript',
      ['decorators', {decoratorsBeforeExport: true}],
      'jsx'
    ],
    ranges: true
  });

// ....
```

**Comment by 43081j** [comment]
yep i think we should have an option to inherit the `babelrc` or at least have a way to pass babel options in.

if you could make an issue for that, that'd be appreciated. if not though, i will when im not mobile 👍

**Comment by iSokrat** [comment]
@43081j 
Created an issue https://github.com/43081j/postcss-lit/issues/44
