### ISSUE TITLE
Not working on VSCode extension

### ISSUE THREAD

**Issue by abdonrd** [43081j/postcss-lit#17]
It works in the CLI, but not in the VSCode extension:

<img width="1148" alt="Screenshot 2021-11-26 at 22 57 10" src="https://user-images.githubusercontent.com/1007051/143657637-10cb2cab-7c52-4025-9390-967bc5ff2414.png">

Example: https://github.com/IBM/pwa-lit-template/compare/stylelint-14

**Comment by 43081j** [comment]
Fixed by #20 as this was just a gap in our knowledge on the extension's settings (i had the same issue).

let me know if it still doesn't work for you and ill reopen

**Comment by abdonrd** [comment]
Oh! Thanks @43081j! 👏🏻
